# Generated by Django 5.1.2 on 2024-10-21 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_software', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_generales', to='ux.rubrica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_generales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(choices=[(1, 'Muy Deficiente'), (2, 'Deficiente'), (3, 'Aceptable'), (4, 'Buena'), (5, 'Excelente')])),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ux.criterio')),
                ('evaluacion_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='ux.evaluaciongeneral')),
            ],
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
