# Generated by Django 5.1.2 on 2024-10-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0002_evaluaciongeneral_calificacion_delete_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
