# Generated by Django 5.1.2 on 2024-10-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0003_calificacion_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='comentario',
        ),
    ]
