# Generated by Django 5.1.2 on 2024-10-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0004_remove_criterio_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='predefinida',
            field=models.BooleanField(default=False),
        ),
    ]
